config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("core.urls", namespace="core")),
    path('rooms/', include("rooms.urls", namespace="rooms")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(template_name="rooms/room_list.html"), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

#                     argument
# urlpatterns = [path("<int:pk>", views.room_detail, name="detail")]
urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoom.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhtos.as_view(), name="photos"),


    path("search/", views.search, name="search")
]

templates/partials/footer.html
<footer>
    &copy; Airbnb
</footer> 

templates/partials/header.html
<header>
    <a href='{% url "core:home" %}'>Airbnb</a>
    <ul>
        <li><a href="#">Login</a></li>
    </ul>
    
    <form method="get" action='{% url "rooms:search" %}'>
<!--        name of input gives argument  -->
        <input name="city" placeholder="Search by City" />
    </form>
</header>