config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("core.urls", namespace="core")),
    path('rooms/', include("rooms.urls", namespace="rooms")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(template_name="rooms/room_list.html"), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

#                     argument
# urlpatterns = [path("<int:pk>", views.room_detail, name="detail")]
urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoom.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhtos.as_view(), name="photos"),


    path("search/", views.search, name="search")
]

rooms/models.py
from django.db import models
from django_countries.fields import CountryField
from django.urls import reverse

from core import models as core_models
from users import models as user_models



class AbstractItem(core_models.TimeStampedModel):
    
    """Abstract Item"""
    
    name = models.CharField(max_length=80)
    
    class Meta:
        abstract = True
        
    
    def __str__(self):
        return self.name
    

    
    # the way i doing this is not to hard-code everything.
    # specific things can be handled at the admin panel.
class RoomType(AbstractItem):
    
    """RoomType Model Definition"""
    class Meta:
        verbose_name = "Room Type"

class Amenity(AbstractItem):
    
    """Amenity Model Definition"""
    
    class Meta:
        verbose_name_plural = "Amenities"

class Facility(AbstractItem):
    
    """Facility Model Definition"""
    
    class Meta:
        verbose_name_plural = "Facilities"

class HouseRule(AbstractItem):
    
    """ HouseRule Model Definition"""
    
    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):
    
    """ Photo Model Definition """
    
    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey(
        "Room", 
        related_name = "photos",
        on_delete=models.CASCADE)
    
    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):
    
    """Room Model Definition"""
    
    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        user_models.User, 
        related_name = "rooms",                     
        on_delete=models.CASCADE)
    room_type = models.ForeignKey(
        RoomType, 
        related_name = "rooms",
        on_delete=models.SET_NULL, 
        null=True
    )
    amenities = models.ManyToManyField(
        Amenity, 
        related_name = "rooms",
        blank=True
    )
    facilities = models.ManyToManyField(
        Facility, 
        related_name = "rooms",
        blank=True)
    house_rules = models.ManyToManyField(
        HouseRule, 
        related_name = "rooms",
        blank=True)
    
    
    # can intercept save. (override)
    # if i want to intercept save event at admin site 
    # using save_model
    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    
    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
#    feature for django admin      
#        reverse get namespace:name and return actual url
        return reverse("rooms:detail", kwargs={"pk": self.pk})
    
    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
        
            return round(all_ratings/len(all_reviews), 2)
        return 0
        
    

rooms/views.py
from math import ceil
from django.shortcuts import render
from django.http import Http404
from django.views.generic import ListView, DetailView, UpdateView
from django.urls import reverse
from django.shortcuts import render, redirect
from . import models
# from users import mixins as user_mixins


#reference-> ccbv.co.uk 
class HomeView(ListView):
    
    
    """ HomeView Definition """
    
    model = models.Room
    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"
    

class RoomDetail(DetailView):
    
    """ RoomDetail Definition """
    
    template_name = "rooms/room_detail.html"
    model = models.Room
# def room_detail(request, pk):
#     try:
#         room = models.Room.objects.get(pk=pk)
#         return render(request, "rooms/detail.html", {"room": room})
#     except models.Room.DoesNotExist:
#  # using reverse will be very helpful..

#         # return redirect(reverse("core:home"))
#         raise Http404()
        
def search(request):
    city = request.GET.get("city")
    city = str.capitalize(city)
    return render(request, "rooms/search.html", {"city": city})


# class EditRoom(user_mixins.LoggedInOnlyView, UpdateView):
class EditRoom(UpdateView):
    
    """ EditRoom Definition"""
    
    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )
    
    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
            
        return room
    
#     this class automatically call get_object function to look for room whose pk is pk
#     so we should override get_object method

# # class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):
class RoomPhotosView(DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room

templates/rooms/detail.html
{% extends "base.html" %}


{% block page_name %}
    Home
{% endblock page_name %}

{% block content %}
<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>
<div>
    <h2>By: {{room.host.username}}
    {% if room.host.superhost %}
        (superhost)
    {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
    {% for a in room.amenities.all  %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>
    {% for a in room.facilities.all  %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
    {% for a in room.house_rules.all  %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
</div>
{% endblock %} 

templates/rooms/room_detail.html
{% extends "base.html" %}


{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}
<div>
     <div class="w-1/3">
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Room</a>
            {% endif %}
        </div>
    <h1>{{room.name}}</h1>
    <h2>
        {{room.city}}
    </h2>
    <h3>{{room.description}}</h3>
</div>
<div>
    <h2>By: {{room.host.username}}
    {% if room.host.superhost %}
        (superhost)
    {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
    {% for a in room.amenities.all  %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>
    {% for a in room.facilities.all  %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
    {% for a in room.house_rules.all  %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
</div>
{% endblock %} 

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Update room" %}
        
         <div class="mt-5">
            <a href="{% url 'rooms:photos' room.pk %}" class="text-teal-500 font-medium">Edit Photos</a>
        </div>

    </div>
{% endblock content %} 

templates/rooms/room_list.html
{% extends "base.html" %}


{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}

    {% for room in rooms  %}
        <h3>
<!--        detail(name) inside of rooms(namespace) and argument
                            /rooms/1    

            url tag          namespace:name  argument
-->
            <a href='{% url "rooms:detail" room.pk %}'>
                {{room.name}} / ${{room.price}}
            </a>
        </h3>
    {% endfor %}

    <h5>
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif %}

        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

        {% if page_obj.has_next  %}
            <a href="?page={{page_obj.next_page_number}}">Next</a>
        {% endif %}


    </h5>
{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col">

        {% for photo in room.photos.all  %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32" />
                    <span class="ml-5 text-xl">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-teal-500" href="#">Edit</a>
                    <a class="btn-link bg-red-600" href="#">Delete</a>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block content %}

    <h2>Search!</h2>

    <h4>Searching by {{city}}</h4>

{% endblock content %}